name: project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.5.1
  provider: ^4.0.1
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


assets:
  - assets/fireIcon.png
  - assets/waterIcon.png
  - assets/grassIcon.png

  - assets/pokemon/arcanine.png
  - assets/pokemon/cinderace.png
  - assets/pokemon/dracovish.png
  - assets/pokemon/greninja.png
  - assets/pokemon/incineroar.png
  - assets/pokemon/kartana.png
  - assets/pokemon/kingdra.png
  - assets/pokemon/rillaboom.png
  - assets/pokemon/venusaur.png

  